### ISSUE TITLE
Gujarati todo

### ISSUE THREAD

**Issue by r12a** [r12a/scripts#126]
- [ ] Add Graphemes section
- [ ] Update line-break section
- [ ] Add baselines & line height section
