### ISSUE TITLE
Georgian todo

### ISSUE THREAD

**Issue by r12a** [r12a/scripts#130]
- [ ] Add Graphemes section
- [x] Update line-break section
- [x] Add baselines & line height section
